# Setup
title:               Cyand
tagline:             'Note taking of thought about something I care'
description:         'Something about Text-to-speech, Deep-learning, and Computer Vision.'
url:                 https://cyand.github.io
baseurl:             /
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Yunchao He
  url:               https://twitter.com/candlewill
  email:             yunchaohe@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1.0
google_analytics_id: UA-35193081-1
