# Setup
title: Cyand
tagline: Just for note taking of my thought about something I care
url: https://cyand.github.io/
paginate: 1
baseurl: https://cyand.github.io/cyand.github.io/
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Yunchao He
  url: https://twitter.com/candlewill
  email: yunchaohe@gmail.com

# Custom vars
version: 0.1.0
